### ISSUE TITLE
app store - app not available in your country (France)

### ISSUE THREAD

**Issue by spointeau** [warrenbuckley/Compact-Log-Format-Viewer#100]
Hello,

Please could you include the country France for your mac app ?
and if possible, make the exec available as part of the release ?

Best regards,
Sylvain

**Comment by warrenbuckley** [comment]
Duplicate of #81 

>I think the metrics for the MacOS usage was little & I don't currently build/release any other Apple apps, so my Apple Developer subscription lapsed. I assumed the application would still be available to download but that I would not be able to push any new updates. However it seems Apple just removes the listing :(
>
>For now I recommend you build it manually. In future I may do auto-updates via GitHub releases instead of app stores.
