### ISSUE TITLE
Locked files won't be read or reloaded

### ISSUE THREAD

**Issue by enkelmedia** [warrenbuckley/Compact-Log-Format-Viewer#106]
**Describe the bug**
Since this app can be used with other implementations of serilog (that locks the file) it would be good to support reading from a locked file as well.

**To Reproduce**
1. Open the app and try to read a file locked by Serilog
2. File can't be read.

**Expected behavior**
The content of the file to be loaded.

PR is comming

**Comment by warrenbuckley** [comment]
Fixed by this PR from @chucker that I finally got around to
https://github.com/warrenbuckley/Compact-Log-Format-Viewer/pull/426
