### ISSUE TITLE
License Not Defined

### ISSUE THREAD

**Issue by mockjv** [warrenbuckley/Compact-Log-Format-Viewer#17]
While this project is published via GitHub, the project itself doesn't have a license defined.  Technically speaking this puts the project in a bit of a weird position if someone were to decide to move forward with any continued development/improvements since it leaves the code in a bit of a "proprietary" state despite the sources being available.

That said, I'm interested in extending/forking the functionality but unsure of whether that's even possible...

**Comment by warrenbuckley** [comment]
Hiya @mockjv 
I will put a license on this tomorrow, as I intend to give this project a tiny bit of love tomorrow.
Out of curiosity what are you missing or wanting to do that the tool currently doesn't do?

**Comment by mockjv** [comment]
@warrenbuckley So, we’re starting to use compact/structured logging in some of our new development, and we were looking at how best to guide users/support to visualize those logs a little better.  Initially we wanted to be able to point them towards this project, but I’m not always comfortable pointing towards projects that don’t have a clear license.  Things he been a bit hectic for me, but once I have a couple of the actual bugs that we experienced reproducible I’ll be sure to snag a screenshot/example log file and submit an issue.
