### ISSUE TITLE
No CLEF log files can be opened

### ISSUE THREAD

**Issue by Sebazzz** [warrenbuckley/Compact-Log-Format-Viewer#313]
**Describe the bug**
No log files created with Serilog.File and the JSON formatter can be openend.

**To Reproduce**
Open the attached log file:
[application20210624 - Copy.zip](https://github.com/warrenbuckley/Compact-Log-Format-Viewer/files/6709721/application20210624.-.Copy.zip)

**Expected behavior**
Log file should be opened; or in the case it is wrong, the error should be handled

**Screenshots**
![image](https://user-images.githubusercontent.com/1426097/123274071-7c2eeb80-d503-11eb-8fb2-e829c8286655.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, Desktop

**Additional context**
This is my Serilog configuration:

```JSON
 "Serilog": {
        "MinimumLevel": {
            "Default": "Information",
            "Override": {
                "Hangfire": "Information",
                "Microsoft": "Warning",
                "Microsoft.Hosting.Lifetime": "Information"
            }
        },
        "WriteTo": [
            {
                "Name": "Async",
                "Args": {
                    "configure": [
                        {
                            "Name": "Console"
                        },
                        {
                            "Name": "File",
                            "Args": {
                                "path": "Logs/application.log",
                                "rollingInterval": "Day",
                                "rollOnFileSizeLimit": true,
                                "shared": true
                            }
                        },
                        {
                            "Name": "File",
                            "Args": {
                                "path": "Logs/application.clef",
                                "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog",
                                "rollingInterval": "Day",
                                "rollOnFileSizeLimit": true
                            }
                        }
                    ] 
                } 
            }
        ],
        "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ],
        "Destructure": [
            {
                "Name": "ToMaximumDepth",
                "Args": { "maximumDestructuringDepth": 4 }
            },
            {
                "Name": "ToMaximumStringLength",
                "Args": { "maximumStringLength": 100 }
            },
            {
                "Name": "ToMaximumCollectionCount",
                "Args": { "maximumCollectionCount": 10 }
            }
        ],
        "Properties": {
            "Application": "[redacted]"
        }
    },

```

I log with:

![image](https://user-images.githubusercontent.com/1426097/123274318-b39d9800-d503-11eb-8425-19a469c02474.png)

**Comment by warrenbuckley** [comment]
Hello @Sebazzz 
Apologies for the long delay.

Debugging with your example file I get the following error, which has highlighted a problem that I need to bubble/surface up this error into the UI.

`The data on line 1 does not include the required `@t` field`
Looking at your JSON file output I see you are using the full names for Properties such as 'Timestamp`, 'Level' and 'MessageTemplate' as opposed to 

`@t` for Timestamp
`@l` for Level
`@mt` for MessageTemplate

Your configuration for formatter should use this Nuget package from the Serilog team and update you configuration
https://github.com/serilog/serilog-formatting-compact

```json
{
  "Serilog": {
    "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "path": ""Logs/application.clef",
          "formatter": "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact",
          "rollingInterval": "Day",
          "rollOnFileSizeLimit": true
        }
      }
    ]
  }
}
```

**Comment by LiorBanai** [comment]
Hi @Sebazzz,
maybe it will be helpful for you my log viewer (https://github.com/Analogy-LogViewer) can open a load your logs. just FYI if still using that  format.
![image](https://user-images.githubusercontent.com/36262995/174646530-71f87b0b-26fa-47fa-ae29-56218f78d057.png)

**Comment by warrenbuckley** [comment]
@Sebazzz i appreciate you being helpful but posting on other open source repositories to a closed/fixed issue to promote your own project is a bit unfriendly in the whole ethos of the Open Source community.

**Comment by Sebazzz** [comment]
> @Sebazzz i appreciate you being helpful but posting on other open source repositories to a closed/fixed issue to promote your own project is a bit unfriendly in the whole ethos of the Open Source community.

<insert gif "It wasn't me">

**Comment by warrenbuckley** [comment]
hahaha sorry @Sebazzz  I was clearly tired and meant to mention @LiorBanai 🙈 

> @LiorBanai I appreciate you being helpful but posting on other open source repositories to a closed/fixed issue to promote your own project is a bit unfriendly in the whole ethos of the Open Source community.

**Comment by LiorBanai** [comment]
Hi @warrenbuckley ,
I'm sorry.  I didn't mean to be unfriendly or disrespect you or your work. I just wanted to be helpful and give more options to the community and the users (someone may find this issue in the future).
Even in my own repositories I someone promote other work or refer to other implementation that may help the issue creator.

But I see how this can be interpreted and will consider this in the future. apologies again.
