### ISSUE TITLE
Allow .log Files to be Imported

### ISSUE THREAD

**Issue by mockjv** [warrenbuckley/Compact-Log-Format-Viewer#40]
**Is your feature request related to a problem? Please describe.**
Currently the app limits imported files to .txt, .json and .clef but our apps still use the .log extension.

**Describe the solution you'd like**
Just need to add more potential extensions to the mix.

**Describe alternatives you've considered**
Might even consider simply checking to see if the file itself is valid JSON, and attempt to load it vs. explicitly enforcing what extensions are allowed.  I also completely understand/respect if this introduces other complexities in your JSON parsing.

**Additional context**
N/A

**Comment by warrenbuckley** [comment]
Fixed in PR from @MonkeyJumps
