### ISSUE TITLE
Broken layout if JSON contains properties with long values

### ISSUE THREAD

**Issue by vzakharov-rxnt** [warrenbuckley/Compact-Log-Format-Viewer#467]
**Describe the bug**
If JSON contains properties with long values, like exception stack trace, the layout ends up broken. I created a reduced test case from the actual ASP.NET Core logs created by Serilog, by anonymizing a small portion of it and removing unnecessary props. It is enough to reproduce the issue I described, please see below screenshot.

```
{"@t":"2022-02-03T14:33:20.9445632Z","@mt":"Application started. Press Ctrl+C to shut down.","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2022-02-03T14:33:20.9757541Z","@mt":"Hosting environment: {envName}","envName":"Development","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2022-02-03T14:33:20.9767532Z","@mt":"Content root path: {contentRoot}","contentRoot":"D:\\Git\\MyProject","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2022-02-03T14:33:21.8817996Z","@mt":"Unhandled exception occured when processing request","@l":"Error","Exception":{"Message":"testing seq","StackTrace":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla egestas malesuada enim, ut euismod ex ornare ac. Vivamus lacinia nec sapien sit amet porttitor. Duis bibendum tellus a auctor iaculis. Vivamus risus ipsum, ullamcorper ut efficitur eget, venenatis in urna. Cras mattis nulla in orci congue fermentum. Nam tempus nulla eu eros dictum sodales. Sed vitae augue vitae Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla egestas malesuada enim, ut euismod ex ornare ac. Vivamus lacinia nec sapien sit amet porttitor. Duis bibendum tellus a auctor iaculis. Vivamus risus ipsum, ullamcorper ut efficitur eget, venenatis in urna. Cras mattis nulla in orci congue fermentum. Nam tempus nulla eu eros dictum sodales. Sed vitae augue vitae ","$type":"ExceptionLogData"},"Application":"MyApplication"}
{"@t":"2022-02-03T14:53:56.1796261Z","@mt":"Application is shutting down...","SourceContext":"Microsoft.Hosting.Lifetime"}
```

**To Reproduce**
1. Drag and drop JSON into Compact Log Viewer.
2. Expand the entry containing the property in question.
3. Observe broken layout.

**Expected behavior**
Column labels should be displayed in a single line, maybe more if they are too long, but definitely not broken down every 1-2 characters. An optional feature could be collapsing long properties by default, but have a clickable ellipsis which allows to expand them. This could be toggled from settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/85562318/152367956-3bf5f57e-4bb5-47f3-a95f-6278cfbc118a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
N/A

**Comment by warrenbuckley** [comment]
Fixed in this PR #470 @vzakharov-rxnt
