### ISSUE TITLE
Logviewer cannot load the log while the site is running

### ISSUE THREAD

**Issue by jmayntzhusen** [warrenbuckley/Compact-Log-Format-Viewer#5]
**Describe the bug**
When you try to load in the current log while the site is running log viewer cannot open the file and gives a weird error screen - it is possibly due to the file being locked?

**To Reproduce**
1. Run a site (IIS Express in VS Code in this instances)
1. Try to open the currently written to log file in the logviewer
1. It is unable to load it and gives this error:
![Capture](https://user-images.githubusercontent.com/36075913/60174809-2ccd5c00-9812-11e9-8217-6ba1ec84988e.PNG)

**Expected behavior**
Expected it to show the log

**Screenshots**
See above

**Desktop (please complete the following information):**
Windows 10

**Comment by warrenbuckley** [comment]
@jmayntzhusen I can not reproduce this in Umbraco 8.1.0+ as @bergmania did a fix in the core of the CMS to deal with file locking stuff, which in turn has fixed/resolved this problem.

So for sites prior to 8.1.0 you will need to have the site stopped to view the logfiles, but for newer 8.1.0 sites the site can be running & the suggestion from Seb #6 would need to be considered, so you can reload/refresh & get the latest results

**Comment by chucker** [comment]
I'm getting the same behavior: while the process is running, Compact Log Viewer never updates the file. In addition, the reload menu item appears to do nothing. It's only when I

* exit the process
* close the file
* reopen it

that I can see changes in CLV.

The same file opened in, say, SnakeTail sees changes immediately.

I'm guessing that the `var firstLine = System.IO.File.ReadLines(filePath).First();` line is the culprit, and have submitted #14.
