### ISSUE TITLE
Update message template hit count to reflect filtered state

### ISSUE THREAD

**Issue by p-m-j** [warrenbuckley/Compact-Log-Format-Viewer#521]
**Is your feature request related to a problem? Please describe.**
No it's an idea for enhancement.

**Describe the solution you'd like**
Hit counts reflect current filter e.g. so it's quick to find the top error message when filtering by log level.

**Describe alternatives you've considered**
Not considdered any alternatives.

**Additional context**
![image](https://user-images.githubusercontent.com/2056399/160441100-b2a2e215-bded-4b83-94a1-de224c27b333.png)

**Comment by warrenbuckley** [comment]
Fixed in PR #530 and in release 1.3.1
