### ISSUE TITLE
Loading of a log file results in an endless loop - different Loglevel casing

### ISSUE THREAD

**Issue by A-Ange** [warrenbuckley/Compact-Log-Format-Viewer#658]
**Describe the bug**
loading of a log file results in an endless loop

**To Reproduce**
1) create a sample file containing "@l": "ERROR" for example  {"@t": "2022-07-01T12:14:15", "@l": "ERROR", "@m": "Test Message"}
2) load that log file
3) change the line to {"@t": "2022-07-01T12:14:15", "@l": "Error", "@m": "Test Message"}
4) now it goes well

**Expected behavior**
loading of the log file

**Desktop (please complete the following information):**
 - OS: WIN 11
 - Version 1.3.2

**Additional context**
[success_log.txt](https://github.com/warrenbuckley/Compact-Log-Format-Viewer/files/9397160/success_log.txt)
[failure_log.txt](https://github.com/warrenbuckley/Compact-Log-Format-Viewer/files/9397162/failure_log.txt)

**Comment by warrenbuckley** [comment]
@A-Ange I can reproduce the error/problem.
Are you not able to set the log level not in caps?

I am currently investigating and seeing how to fix this up, but I think it's the external library that I am using that I will need to do a PR for perhaps.

**Comment by warrenbuckley** [comment]
As suspected this is an issue with the Nuget package this depends on `Serilog.Formatting.Compact.Reader`
https://github.com/serilog/serilog-formatting-compact-reader/pull/34
