### ISSUE TITLE
Show possible search filters via the help menu

### ISSUE THREAD

**Issue by howest-dieter** [warrenbuckley/Compact-Log-Format-Viewer#66]
It is not apparent for a user what search filters can be used.

Via the 'Help' menu item there is a link to the Git repo.
![image](https://user-images.githubusercontent.com/46340164/85853073-29b4d500-b7b2-11ea-9179-a1efcf538d60.png)

At the end of the page (the readme.md) there is a mention of the SeriLog Filters Expressions.

Suggestions:

- In the readme.md: Link to https://github.com/serilog/serilog-filters-expressions + include a short explanation
- In the UI of the app: Add a menu item under 'Help' for a new modal that lists the possible search filters

**Comment by warrenbuckley** [comment]
Started a draft PR here https://github.com/warrenbuckley/Compact-Log-Format-Viewer/pull/445

Here is a quick look at it so far but I need to document more examples in this new HTML page

![image](https://user-images.githubusercontent.com/1389894/150161749-a6f77fa6-3074-491f-8b9a-1af1fa1a57df.png)

**Comment by Didjeeh** [comment]
Cool. Nicely done.
