### ISSUE TITLE
Word-wrap long titles/errors etc

### ISSUE THREAD

**Issue by nul800sebastiaan** [warrenbuckley/Compact-Log-Format-Viewer#7]
When titles or errors get a bit long, the're no wrapping so there's a very long horizontal scroll. Would be good with some word-wrapping. 

Examples:

![image](https://user-images.githubusercontent.com/304656/60325475-a76bb800-9987-11e9-8b88-593eb75534a5.png)

![image](https://user-images.githubusercontent.com/304656/60325489-b3577a00-9987-11e9-9921-7fe77e4820b7.png)

**Comment by warrenbuckley** [comment]
This is fixed already in the local development build but has yet to be pushed out to Windows Store. Will be in 1.0.6 next release
