### ISSUE TITLE
Limited support for destructed properties

### ISSUE THREAD

**Issue by enkelmedia** [warrenbuckley/Compact-Log-Format-Viewer#704]
I know that this PR added "Basic support" for destructed properties https://github.com/warrenbuckley/Compact-Log-Format-Viewer/pull/15, how every since this implementation only supports nesting to the first level it's kind of limiting.

I've just made a PR to Umbraco (almost the same code as this) with another approach: https://github.com/umbraco/Umbraco-CMS/pull/13357

I'm not saying that this is perfect but it makes is possible to see the whole object structure.

Let me know if you think that this might be something for this app, I'd be happy to create a PR.

Cheers!

**Comment by warrenbuckley** [comment]
Fixed in https://github.com/warrenbuckley/Compact-Log-Format-Viewer/pull/707
