### ISSUE TITLE
To be able to aggregate on @Exception

### ISSUE THREAD

**Issue by howest-dieter** [warrenbuckley/Compact-Log-Format-Viewer#99]
When for instance one uses Serilog in an API to log errors and that API has a bug in it and it is accessed numerous times, the same error will get logged multiple times. 

This is fine. Still it would be handy if one could aggregate / select distinct on @Exception.
Inspiration [https://github.com/waxtell/Serilog.Aggregating.Filter](https://github.com/waxtell/Serilog.Aggregating.Filter) (but than after logging to file happens and not before)

This will make analyzing log files much faster than messing around with _like / not like_ filters.

Example log file:
[20201005.zip](https://github.com/warrenbuckley/Compact-Log-Format-Viewer/files/5332908/20201005.zip)

**Comment by warrenbuckley** [comment]
Hello @howest-dieter 
I am not entirely sure how I can implement this in the LogViewer and seems like the Serilog.Aggregating.Filter will do this work for you when it sends the logs on to the one or more sinks. Be it a text file or a third party system.

For now I will close this issue, unless you have a specific idea or solution for me to implement this.

**Comment by howest-dieter** [comment]
That's fine. I can build something that does this. Thanks.

**Comment by warrenbuckley** [comment]
If you feel it could be useful to this project feel free to contribute a PR back @howest-dieter
